# Uncomment this line to define a global platform for your project
# platform :ios, '7.0'

target 'WeddingWise' do

pod 'AFNetworking', '2.5.1'
pod 'MBProgressHUD', '~> 0.8'
pod 'SCNetworkReachability'

end

target 'WeddingWiseTests' do

end

